<Project>
    <PropertyGroup>
        <ValheimGamePath>D:\SteamLibrary\steamapps\common\Valheim</ValheimGamePath>
        <BepInExPath>$(AppData)\r2modmanPlus-local\Valheim\profiles\Test\BepInEx</BepInExPath>
        <CorlibPath>$(ValheimGamePath)\valheim_Data\Managed</CorlibPath>
        <PublicizedAssembliesPath>$(ValheimGamePath)\valheim_Data\Managed\publicized_assemblies</PublicizedAssembliesPath>
        <CopyOutputDLLPath>$(AppData)\r2modmanPlus-local\Valheim\profiles\Test\BepInEx\plugins\DaiMinhTri-FishChum</CopyOutputDLLPath>
        <AfterTargets>ILRepacker</AfterTargets>
    </PropertyGroup>
</Project>
